### ISSUE TITLE
Won't run...

### ISSUE THREAD

**Issue by everythingability** [jeonghopark/SketchSynthVideo-Simple#1]
Hi,

I'm on 10.15.5 (19F96) and I get this when I run the .app

<img width="452" alt="Screenshot 2020-07-21 at 17 13 19" src="https://user-images.githubusercontent.com/96276/88079760-1230f800-cb76-11ea-83ed-7939b7edfa3d.png">

Tom

**Comment by jeonghopark** [comment]
It's a just warning message from mac os. You can cancel and then follow the next steps.

Mac Version
SECURITY STEPS REQUIRED BY APPLE
After download, the first time you run the application, it will appear a security alert.
Open the System Preferences "Security & Privacy - General" pane.
If you see an "Open Anyway" button in the Security Preferences, click the "Open Anyway" button.
Then click the "Open" button in that window to launch the application.

**Comment by everythingability** [comment]
Nope. Warning comes up.  Click cancel, app stops loading.

**Comment by jeonghopark** [comment]
It's normal. Now open the system preferences "Security & Privacy".

**Comment by jeonghopark** [comment]
I have uploaded a new build. Please check.

**Comment by everythingability** [comment]
Haha! That's fixed it. Thank you very much.
